### ISSUE TITLE
Twitter APIの調査

### ISSUE THREAD

**Issue by great084** [great084/twitter_tool#2]
## 概要
要件を満たすために使用するTwitter APIの調査を行う

## 内容
以下の機能を実装するために、使用するAPIおよびAPI利用のための条件（法人アカウント？）などを調査する。
また、API利用の制約（１度の上限件数など）の整理も行う
- Twitterログイン認証
- 過去の投稿のエンゲージメントを取得
- 過去の投稿に対する、リツートor再ツイート

**Comment by domi10momo** [comment]
### Twitterログイン認証
Twitter api ver 1.1  または ver 2 が使用可能
ver2 は今年発表されたもので、ツイート投稿に対応していないようなので、ver 1.1にて調査
（しかし、最終的にはver 2に完全移行とのこと）

#### Twitter api ver 1.1
- Standard
　無料にて使用可能。しかし、過去7日分のツイートしか検索できないため、却下

- Enterprize
　有料。企業用のアカウントのため高額

- Premium
　一部無料にて使用可能。機能をカスタムしていくことで随時課金。

<無償と有償の機能の違い>
　- リクエストごとのツイート数を増やす
　- より高いレート制限
　- ツイートの時系列カウントを返すカウントエンドポイント
　- より複雑なクエリ
　- 拡張されたURLや改善されたプロファイル地理情報などのメタデータの強化

<無料で使用出来る機能>
- ツイート検索できる期間：Twitter開設時から現在まで（2006年〜のデータ）
- リクエスト毎に取得できるツイート：100件
- 取得するデータをカウントすることはできない
- クエリの長さ：128文字
- 検索条件を絞る演算子の種類：プレミアムより制限はかかる
- 1分あたり30回リクエスト可能
- 月間最大5000ツイートまで取得可能

[機能比較](https://developer.twitter.com/en/pricing/search-fullarchive)


### ツイートの取得
<エンドポイント>
https://api.twitter.com/1.1/search/tweets.json

<br>

<ある人がある期間にしたツイートを取得したい場合>
| 演算子 | 検索するツイート|
|--------|------------------|
| from:alexiskold | “alexiskold”さんから送られたツイート |
| superhero since:2010-12-27 | "superhero” を含み、 “2010-12-27” (年-月-日)以降に送られたツイート。|
| ftw until:2010-12-27 | “ftw” を含み、“2010-12-27”以前に送られたツイート |

<br>

<いいね数、RT数取得(pythonのサンプル)>
res = twitter.get(url, params = params)
tweets = json.loads(res.text)
tweet_list = tweets["results"]

for tweet in tweet_list:
      retweet_count.append(tweet["retweet_count"]) #リツイート数
      favorite_count.append(tweet["favorite_count"]) #いいね数


### ツイート投稿

<エンドポイント>
POST https://api.twitter.com/1.1/statuses/update.json

< 制限>
ツイートおよびリツイート（合算値）　3時間内300件まで<br>
 
<apiを使用したツイート投稿コード>
[参考コード](https://programming-beginner-zeroichi.jp/articles/64)

**Comment by great084** [comment]
@domi10momo 
調査ありがとうございます。サンプルコードなど詳細な部分まで調べていただき、驚きました。

今回の調査を元に、次回のミーティングでどのプランを適用するのかを、ヒアリングして確認していきましょう。

以下、質問・コメントです。

【機能】
エンゲージメント数(いいね、リツイート、メディア・ハッシュタグ・プロフィールなど各種クリック数、の総数)を取得する場合には、Enterprise版ではないと取得できないという記事をいくつか見かけたのですが、相違ないでしょうか？
その場合Standard/Plemium版ではどこまで取得できるのか（ex. いいね、リツイートはOKだけど他はとれない）を明確にして、ほしいです。

【ボリューム】
上記の調査結果でも言及してもらいましたが、プランごとの上限などの制約を整理してほしいです。

【コスト】
APIアカウント取得にかかるコストをStandard/Plemium/Enterprise版それぞれで整理してほしいです。


以上の、【機能】【ボリューム】【コスト】がStandard/Plemium/Enterprise版ごとに一覧化した整理資料を作っていただけないでしょうか？

**Comment by domi10momo** [comment]
> エンゲージメント数(いいね、リツイート、メディア・ハッシュタグ・プロフィールなど各種クリック数、の総数)を取得する場合には、Enterprise版ではないと取得できないという記事をいくつか見かけたのですが、相違ないでしょうか？

すみません、私も明確な機能の基準まで調査できていませんでした。
本日調査し、結論としてはEnterprise版でないとエンゲージメント数は取得できないという認識で問題ありません。

内容としては、Standard/Premium/Enterprise全てにおいて、検索用のAPIは「いいね数」「リツイート数」のみが取得できること確認しました。
しかし、エンゲージメントの他の値を取得するには、別にEngagement APIというAPIを使用する必要があり、それがEnterprise版でしか使用できない機能のため上記の結果となりました。

まず、ご連絡でした。これからその他については整理しますので少々お待ちください。

**Comment by domi10momo** [comment]
ファイルにStandard/Premium/Enterpriseの機能、条件、価格まとめました。
Engagement APIもプランによっては2014年以降のツイートの各エンゲージメント取得可能。
ただ、Enterpriseは金額が現時点で正確に確認できないのが難点です。

[各プラン機能内容.xlsx](https://github.com/great084/twitter_tool/files/5465668/default.xlsx)

**Comment by great084** [comment]
> 本日調査し、結論としてはEnterprise版でないとエンゲージメント数は取得できないという認識で問題ありません。
> 
> 内容としては、Standard/Premium/Enterprise全てにおいて、検索用のAPIは「いいね数」「リツイート数」のみが取得できること確認しました。
> しかし、エンゲージメントの他の値を取得するには、別にEngagement APIというAPIを使用する必要があり、それがEnterprise版でしか使用できない機能のため上記の結果となりました。

なるほど〜
エンゲージメント数を取得するEngagement APIは、Enterprise版しか利用できないんですね。
ありがとうございます。

**Comment by great084** [comment]
@domi10momo 
昨日のミーティングで話したように、プランはpremium(sandbox)フルアーカイブとすることになりました。
つきましては、過去投稿情報で取得できる項目の一覧を調査していただけますか？
DB定義のインプットになると考えています。
整理していただいた情報はwiki（リンク可）に掲載お願いします。

**Comment by domi10momo** [comment]
@great084 
かしこまりました。調査しwikiに掲載します。

**Comment by domi10momo** [comment]
パラメータ調査し、wikiに掲載したためイシュをクローズいたします。
